version: '3.8'

services:
  score-engine:
    build: .
    container_name: score-engine
    ports:
      - "50051:50051"
    volumes:
      - ./database.db:/app/database.db
    restart: unless-stopped
