apiVersion: v1
kind: Service
metadata:
  name: ticket-score-engine
spec:
  selector:
    app: ticket-score-engine
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP